# Generated by Django 3.1.7 on 2021-04-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(help_text='добавте теги', to='main.Tag'),
        ),
    ]
